name: Build and Deploy Docker Image to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17' 

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: ems-backend

    - name: Build Docker image
      run: docker build -t ${{ secrets.ACR_URL }}/ems-backend:${{ github.sha }} .
      working-directory: ems-backend

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_URL }} 
        username: ${{ secrets.AZURE_USERNAME }} 
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Push Docker image to Azure Container Registry
      run: docker push ${{ secrets.ACR_URL }}/ems-backend:${{ github.sha }}

    - name: Logout from Docker
      run: docker logout ${{ secrets.ACR_URL }}
