name: Build and Deploy Docker Image to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17' 

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: ems-backend

    - name: Build Docker image
      run: docker build -t ${{ secrets.ACR_URL }}/ems-backend:${{ github.sha }} .
      working-directory: ems-backend

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_URL }} 
        username: ${{ secrets.AZURE_USERNAME }} 
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Push Docker image to Azure Container Registry
      run: docker push ${{ secrets.ACR_URL }}/ems-backend:${{ github.sha }}

    # - name: Logout from Docker
    #   run: docker logout ${{ secrets.ACR_URL }}
    
    - name: Az CLI login
      uses: azure/login@v2
      with:
          client-id: 9da63db1-12cd-4f3f-8763-74d6d9fa83e4
          subscription-id: n0d8Q~bsu1feWBUWPlFrMsmW-xH0QgcT9tUTTa~0
          tenant-id: 35e9f023-8c53-4774-87e7-156bbe96651d

          
    - name: Deploy container to Azure Container Instance
      run: |
       # az account set --subscription "2ba31480-ee6e-422e-a54b-f6c74b504f47" --debug
       az container create \
         --resource-group ems-backend-rg \
         --name emsaci \
         --image ${{ secrets.ACR_URL }}/ems-backend:${{ github.sha }} \
         --cpu 1 \
         --memory 1.0 \
         --restart-policy OnFailure
         --registry-password ${{ secrets.AZURE_PASSWORD }} \
         --os-type Linux \
         --ports 80
